### PR TITLE
Added AnyTone AT-D878UV as copy of AT-D868UV

### PR DESCRIPTION
**Pull request by KD4PPG**
Extremely basic modification, seems to work so far on my AT-D878UV

### CODE REVIEW

**Comment by sergev** [comment]
Jim, thank you for the patch!

**Comment by KD4PPG** [comment]
Serge,

Your code was clean and easy to follow, and the 878 is so close to the 868 that it was really easy to make the changes.

However, I realized I missed one place in radio.c, in radio_read_image(), so I'm sending you another pull request.  I do apologize for the oversight.

There are some differences in the versions that I'm probably just not running into.  If I can provide any kind of files or anything to be more thorough, just let me know.

Thanks,
Jim

**Comment by sergev** [comment]
That's OK - I just merged your second pull request. It would be helpful if you send me a binary image of d878uv, for my collection. May be a factory image, right after software reset. So I could compare it with d868uv and figure out the differences. Thank you.

**Comment by KD4PPG** [comment]
I'll try to do that tonight, and get that to you.

Have you started work on adding support for the CS800D by any chance?

Thanks,
jim

**Comment by KD4PPG** [comment]
Serge,

I've done a factory reset and used dmrconfig -r to get device.img and device.conf, which are attached.  Additionally, when I first got the radio, I did an initial CP read and saved it for archival purposes, and I've attached that as well.

When I bought it, it had firmware 1.06, and now it's at firmware 1.09, not sure if that will make any difference.  I can re-read via windows after a reset if you need that as well.

Before I did the factory reset, I made a backup with dmrconfig -r, and after pulling the blank config for you, I wrote the backup back with dmrconfig -w, and it even put my on-screen channel selections back where they were.

Please let me know if you need anything else from me to help make this radio better supported.  I'll do anything I'm capable of to help.

Thanks,
Jim

**Comment by sergev** [comment]
> Have you started work on adding support for the CS800D by any chance?

Unfortunately, I don't have access to CS800D. The format of the codeplug file (RDB) looks pretty simple. The protocol can be reverse engineered with USB sniffer.

**Comment by sergev** [comment]
> I've done a factory reset and used dmrconfig -r to get device.img and device.conf, which are attached.

Thank you, Jim! I still don't see any attached files.

> Before I did the factory reset, I made a backup with dmrconfig -r, and after pulling the blank config for you, I wrote the backup back with dmrconfig -w, and it even put my on-screen channel selections back where they were.

So dmrconfig works pretty well with D878UV. Excellent!

**Comment by KD4PPG** [comment]
I was afraid an attachment wouldn't work.

Perhaps this dropbox link will?
https://www.dropbox.com/sh/dw9d5gmod4g894y/AAC1r0k_Pg6vCkH6i0VOjWPNa?dl=0 <https://www.dropbox.com/sh/dw9d5gmod4g894y/AAC1r0k_Pg6vCkH6i0VOjWPNa?dl=0>

If not, let me know and I'll try to find another way to get the files to you.

Jim

**Comment by KD4PPG** [comment]
I understand.  I'm using a raspberry pi which I can keep powered up in the car overnight with the radio on while I ssh in and try to figure out how to talk to it.

lsusb shows this:
Bus 001 Device 005: ID 0483:5720 STMicroelectronics STM microSD Flash Device

I've added the device tag into radio.c in a branch, as such:

    if (! ident) {
        // Try CS800D.
        if (hid_init(0x0483, 0x5720) >= 0)
            fprintf(stderr, "CS800D debug.\n");
            ident = hid_identify();
    }

When I run dmrconfig -r, I get this:

sudo ../dmrconfig/dmrconfig -r -t
Cannot find USB device 0483:df11
Cannot find USB device 15a2:0073
CS800D debug.
---Send 01 00 07 00 02 50 52 4f 47 52 41
Error -9 transmitting data via control transfer: Pipe error

The sudo is to get around any device permission problems, which I figure I can solve with an update to 99-dmr.rules once it's all hashed out.

I'm not sure how to go about sniffing usb.  Ethernet is easy, but how would I go about it with usb?  Wireshark on the windows laptop?

Thanks for any pointers you can provide,
Jim

**Comment by sergev** [comment]
Got the files: a lot of thanks! I use thes images for regression testing.

For RD-5R, I was able to reconstruct the protocol using [Winpcap](https://www.winpcap.org/) to dump the USB traffic to a PCAP file. With native CPS, I made two pcap files: for reading a codeplug from the radio, and for writing to the radio. Raw binary data are here:

[rd5r-read.pcap](https://raw.githubusercontent.com/wiki/sergev/dmrconfig/files/rd5r/rd5r-read.pcap)
[rd5r-write.pcap](https://raw.githubusercontent.com/wiki/sergev/dmrconfig/files/rd5r/rd5r-write.pcap)

Then, I wrote a couple of Python scripts to decode the pcap files:

[pcap-read.py](https://raw.githubusercontent.com/wiki/sergev/dmrconfig/scripts/pcap-read.py)
[pcap-write.py](https://raw.githubusercontent.com/wiki/sergev/dmrconfig/scripts/pcap-write.py)

The scripts produce the following trace files:

[rd5r-read.log](https://raw.githubusercontent.com/wiki/sergev/dmrconfig/files/rd5r/rd5r-read.log)
[rd5r-write.log](https://raw.githubusercontent.com/wiki/sergev/dmrconfig/files/rd5r/rd5r-write.log)

Same method should work for CS800D as well.

**Comment by KD4PPG** [comment]
I'll give that a shot tomorrow, and see what progress I can make.  I'll backup the existing config, factory reset, and start from there.  A capture of read, another of write, then parse them, and see what I can see, and see if I can turn that into code.

I'll share the files with you once I have them created.  I'll include the .rdt as well.

**Comment by KD4PPG** [comment]
Serge,

I used wireshark to capture the packets.  I did 3 different captures, one with just connecting the radio, then disconnecting it.  The second was connect, read, disconnect.  The third was connect, write, wait for reboot (a disconnect/reconnect cycle in USB), then disconnect.

Wireshark saves the files as a "next generation" pcap file.  Fortunately, tshark still understands them, although the layers are a little different.  Also, any packet originating from the host had the address 'host', so I separated send and receive by 'host' and not 'host'.

I also saved the file in the native software (.rdb format).  I've bundled it all up into a zip file:

[cs800d.zip](https://github.com/sergev/dmrconfig/files/2668321/cs800d.zip)

I'm honestly over my head at this point, since I don't have a lot of knowledge about USB protocol.

Do you think this is enough information to work with?

**Comment by KD4PPG** [comment]
also, not sure if you know, but Connect Systems Inc is just rebranding a chinese DMR radio made by covalue.

http://en.covalue.cn/products_detail/productId=48.html
DM6000 is their model # for the same thing.

**Comment by sergev** [comment]
> I used wireshark to capture the packets. I did 3 different captures, one with just connecting the radio, then disconnecting it. The second was connect, read, disconnect. The third was connect, write, wait for reboot (a disconnect/reconnect cycle in USB), then disconnect.

Jim, are you sure you captured correct USB bus? I cannot find any meaningful data here. 

> also, not sure if you know, but Connect Systems Inc is just rebranding a chinese DMR radio made by covalue.

I suspected CSI is just a reseller. Didn't know the manufacturer is Covalue.

**Comment by KD4PPG** [comment]
I was afraid you'd say something like that...

I'm positive I wasn't getting any other USB bus data.  The capture was totally quiet until plugging in the radio, and after unplugging the radio it went totally quiet again after several seconds.

Digging through the wireshark capture, I could see that almost all the traffic between the host and the radio was done using the mass storage protocols, and the radio showed up looking like a flash drive, although with no partition table or other typical block device attributes.

I'm going to see if I can run a debugger on the actual CPS and see what function calls it is using when reading/writing.  I suspect that it's doing direct "disk" read and write, using pre-known addresses for the CPS records.

Looking in dmrconfig, I don't see support for anything other than HID or Serial interfacing, so this would be something new.  Looks like I have a lot more to learn in order to be able to contribute with this radio. LOL

Thanks for taking the time to look at it.  After this weekend, my shack will be better arranged for me to do further experimenting with this.

**Comment by sergev** [comment]
The USB traffic indeed looks like disk i/o. But the data portion seems too short. The codeplug size is 420k, so all these data have to be present in the pcap files. Could you try the same with Winpcap?

Currently dmrconfig does nos support this type of i/o. But adding it is not the most complicated part of the task.

**Comment by KD4PPG** [comment]
Ok, I'll configure a machine with winpcap and capture again.

This'll have to wait for the weekend, as my workshop is getting new work surfaces this weekend then I'll have room to work on it.

I definitely want to follow up on this, and I really appreciate all of your assistance with it.  I'll contact you again as soon as I do another set of captures.

**Comment by KD4PPG** [comment]
I've not forgotten about this, however I've been unable to get any better capture with the equipment I have.

Is the CS800D a radio you want to support?  If so, could I send it to you for investigation?  I'm planning to remove it from my vehicle soon, and eventually intend to sell it.  My 878 is such a better operational experience that I use it for everything now.

**Pull request merged**
